name: practica-ghactions-workflow
on: [push]
jobs:
  Linter_job:
    runs-on: ubuntu-latest
    name: Linter job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Check syntax
        run: |
          npm install
          npm run lint
  
  Cypress_job:
    needs: Linter_job
    runs-on: ubuntu-latest
    name: Cypress job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Cypress tests
        if: always()
        id: cypress-tests
        uses: cypress-io/github-action@v2
        with:
          build: npm run build
          start: npm start
      - name: Add cypress tests outcome to file
        run: echo ${{ steps.cypress-tests.outcome }} > result.txt
      - name: Create artifact
        uses: actions/upload-artifact@v2
        with:
          name: result-artifact
          path: ./result.txt
  
  Add_badge_job:
    needs: Cypress_job
    runs-on: ubuntu-latest
    name: Add badge job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get artifacts
        with:
          name: result-artifact
      - name: Generate result output
        id: test-result-step
        run: echo "::set-output name=cypress-result::$(cat result.txt)"
      - name: Update README badge
        uses: ./.github/actions/readmeAction
        with:
          cypress-result: ${{ steps.test-result-step.outputs.cypress-result }}
      - name: Commit README
        run: |
          git config user.email "samaelgomezherrera@gmail.com"
          git config user.name "samaelgomez"
          git add .
          git commit -m "README badge update"
          git push origin master