name: practica-ghactions-workflow
on: [push]
jobs:
  Linter_job:
    runs-on: ubuntu-latest
    name: Linter job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Check syntax
        run: |
          npm install
          npm run lint
  
  Cypress_job:
    needs: Linter_job
    runs-on: ubuntu-latest
    name: Cypress job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Cypress tests
        if: always()
        id: cypress-tests
        uses: cypress-io/github-action@v2
        with:
          build: npm run build
          start: npm start
      - name: Add cypress tests outcome to file
        run: echo ${{ steps.cypress-tests.outcome }} > result.txt
      - name: Create artifact
        uses: actions/upload-artifact@v2
        with:
          name: Result artifact
          path: ./result.txt